// Autogenerated from vk-api-schema. Please don't edit it manually.
package com.vk.api.sdk.objects.messages;

import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;
import com.vk.api.sdk.objects.Validable;
import com.vk.api.sdk.objects.annotations.Required;
import com.vk.api.sdk.objects.base.Geo;

import java.util.List;
import java.util.Objects;

/**
 * PinnedMessage object
 */
public class PinnedMessage implements Validable {
    @SerializedName("attachments")
    private List<MessageAttachment> attachments;

    @SerializedName("attachments")
    private List<List<String>> rawAttachments;

    /**
     * Unique auto-incremented number for all messages with this peer
     */
    @SerializedName("conversation_message_id")
    @Required
    private Integer conversationMessageId;

    /**
     * Date when the message has been sent in Unixtime
     */
    @SerializedName("date")
    @Required
    private Integer date;

    /**
     * Message author's ID
     * Entity: owner
     */
    @SerializedName("from_id")
    @Required
    private Long fromId;

    /**
     * Forwarded messages
     */
    @SerializedName("fwd_messages")
    private List<ForeignMessage> fwdMessages;

    @SerializedName("geo")
    private Geo geo;

    /**
     * Message ID
     */
    @SerializedName("id")
    @Required
    private Integer id;

    /**
     * Is it an important message
     */
    @SerializedName("important")
    private Boolean important;

    @SerializedName("keyboard")
    private Keyboard keyboard;

    /**
     * Information whether the message is outcoming
     */
    @SerializedName("out")
    private Boolean out;

    /**
     * Peer ID
     * Entity: peer
     */
    @SerializedName("peer_id")
    @Required
    private Long peerId;

    @SerializedName("reply_message")
    private ForeignMessage replyMessage;

    /**
     * Message text
     */
    @SerializedName("text")
    @Required
    private String text;

    public List<MessageAttachment> getAttachments() {
        if (attachments != null) {
            return attachments;
        }
        // Convert raw array format to MessageAttachment objects
        if (rawAttachments != null) {
            return convertRawAttachments(rawAttachments);
        }
        return null;
    }

    private List<MessageAttachment> convertRawAttachments(List<List<String>> rawAttachments) {
        List<MessageAttachment> result = new ArrayList<>();
        
        for (List<String> rawAttachment : rawAttachments) {
            if (rawAttachment.size() >= 2) {
                MessageAttachment attachment = createMessageAttachmentFromArray(rawAttachment);
                if (attachment != null) {
                    result.add(attachment);
                }
            }
        }
        return result;
    }

    private MessageAttachment createMessageAttachmentFromArray(List<String> rawAttachment) {
        String type = rawAttachment.get(0);
        String data = rawAttachment.get(1);
        
        MessageAttachment attachment = new MessageAttachment();
        attachment.setType(type); // Set the attachment type
        
        // Handle different attachment types
        switch (type) {
            case "photo":
                return createPhotoAttachment(data);
            case "audio":
                return createAudioAttachment(data);
            case "video":
                return createVideoAttachment(data);
            case "doc":
                return createDocumentAttachment(data);
            case "link":
                return createLinkAttachment(data, rawAttachment);
            // Add other types as needed
            default:
                log.warn("Unhandled attachment type: {}", type);
                return createGenericAttachment(type, data);
        }
    }

    private MessageAttachment createPhotoAttachment(String photoData) {
        MessageAttachment attachment = new MessageAttachment();
        attachment.setType("photo");
        
        // Parse photo ID format: "owner_id_photo_id"
        String[] parts = photoData.split("_");
        if (parts.length >= 2) {
            try {
                // Create a Photo object that the SDK expects
                Photo photo = new Photo();
                photo.setOwnerId(Long.parseLong(parts[0]));
                photo.setId(Integer.parseInt(parts[1]));
                
                // Set the photo object in the attachment
                // This depends on the SDK's MessageAttachment structure
                attachment.setPhoto(photo);
                
            } catch (NumberFormatException e) {
                log.error("Failed to parse photo data: {}", photoData, e);
            }
        }
        return attachment;
    }

    private MessageAttachment createAudioAttachment(String audioData) {
        MessageAttachment attachment = new MessageAttachment();
        attachment.setType("audio");
        
        try {
            // Audio format: "owner_id_audio_id"
            String[] parts = audioData.split("_");
            if (parts.length >= 2) {
                Audio audio = new Audio();
                audio.setOwnerId(Long.parseLong(parts[0]));
                audio.setId(Integer.parseInt(parts[1]));
                attachment.setAudio(audio);
            }
        } catch (NumberFormatException e) {
            log.error("Failed to parse audio data: {}", audioData, e);
        }
        return attachment;
    }

    private MessageAttachment createVideoAttachment(String videoData) {
    MessageAttachment attachment = new MessageAttachment();
    attachment.setType("video");
    
    try {
            // Video format: "owner_id_video_id" or "owner_id_video_id_access_key"
            String[] parts = videoData.split("_");
            if (parts.length >= 2) {
                Video video = new Video();
                video.setOwnerId(Long.parseLong(parts[0]));
                video.setId(Integer.parseInt(parts[1]));
                
                if (parts.length >= 3) {
                    video.setAccessKey(parts[2]);
                }
                attachment.setVideo(video);
            }
        } catch (NumberFormatException e) {
            log.error("Failed to parse video data: {}", videoData, e);
        }
        return attachment;
    }

    private MessageAttachment createLinkAttachment(String linkData, List<String> rawAttachment) {
        MessageAttachment attachment = new MessageAttachment();
        attachment.setType("link");
        
        // Link might have additional data in the array
        Link link = new Link();
        link.setUrl(linkData); // First element might be URL
        
        if (rawAttachment.size() > 2) {
            // Additional link metadata might be in subsequent array elements
            link.setTitle(rawAttachment.size() > 2 ? rawAttachment.get(2) : null);
            link.setDescription(rawAttachment.size() > 3 ? rawAttachment.get(3) : null);
        }
        
        attachment.setLink(link);
        return attachment;
    }

    // Fallback for unhandled types
    private MessageAttachment createGenericAttachment(String type, String data) {
        MessageAttachment attachment = new MessageAttachment();
        attachment.setType(type);
        
        // Store raw data in a way that doesn't break the SDK
        // This might involve using a custom field or additional properties
        log.debug("Created generic attachment for type: {} with data: {}", type, data);
        return attachment;
    }

    public PinnedMessage setAttachments(List<MessageAttachment> attachments) {
        this.attachments = attachments;
        return this;
    }

    public Integer getConversationMessageId() {
        return conversationMessageId;
    }

    public PinnedMessage setConversationMessageId(Integer conversationMessageId) {
        this.conversationMessageId = conversationMessageId;
        return this;
    }

    public Integer getDate() {
        return date;
    }

    public PinnedMessage setDate(Integer date) {
        this.date = date;
        return this;
    }

    public Long getFromId() {
        return fromId;
    }

    public PinnedMessage setFromId(Long fromId) {
        this.fromId = fromId;
        return this;
    }

    public List<ForeignMessage> getFwdMessages() {
        return fwdMessages;
    }

    public PinnedMessage setFwdMessages(List<ForeignMessage> fwdMessages) {
        this.fwdMessages = fwdMessages;
        return this;
    }

    public Geo getGeo() {
        return geo;
    }

    public PinnedMessage setGeo(Geo geo) {
        this.geo = geo;
        return this;
    }

    public Integer getId() {
        return id;
    }

    public PinnedMessage setId(Integer id) {
        this.id = id;
        return this;
    }

    public Boolean getImportant() {
        return important;
    }

    public PinnedMessage setImportant(Boolean important) {
        this.important = important;
        return this;
    }

    public Keyboard getKeyboard() {
        return keyboard;
    }

    public PinnedMessage setKeyboard(Keyboard keyboard) {
        this.keyboard = keyboard;
        return this;
    }

    public Boolean getOut() {
        return out;
    }

    public PinnedMessage setOut(Boolean out) {
        this.out = out;
        return this;
    }

    public Long getPeerId() {
        return peerId;
    }

    public PinnedMessage setPeerId(Long peerId) {
        this.peerId = peerId;
        return this;
    }

    public ForeignMessage getReplyMessage() {
        return replyMessage;
    }

    public PinnedMessage setReplyMessage(ForeignMessage replyMessage) {
        this.replyMessage = replyMessage;
        return this;
    }

    public String getText() {
        return text;
    }

    public PinnedMessage setText(String text) {
        this.text = text;
        return this;
    }

    @Override
    public int hashCode() {
        return Objects.hash(date, peerId, keyboard, attachments, fromId, out, geo, important, fwdMessages, conversationMessageId, replyMessage, id, text);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        PinnedMessage pinnedMessage = (PinnedMessage) o;
        return Objects.equals(date, pinnedMessage.date) &&
                Objects.equals(keyboard, pinnedMessage.keyboard) &&
                Objects.equals(attachments, pinnedMessage.attachments) &&
                Objects.equals(fromId, pinnedMessage.fromId) &&
                Objects.equals(conversationMessageId, pinnedMessage.conversationMessageId) &&
                Objects.equals(out, pinnedMessage.out) &&
                Objects.equals(peerId, pinnedMessage.peerId) &&
                Objects.equals(geo, pinnedMessage.geo) &&
                Objects.equals(important, pinnedMessage.important) &&
                Objects.equals(fwdMessages, pinnedMessage.fwdMessages) &&
                Objects.equals(id, pinnedMessage.id) &&
                Objects.equals(text, pinnedMessage.text) &&
                Objects.equals(replyMessage, pinnedMessage.replyMessage);
    }

    @Override
    public String toString() {
        final Gson gson = new Gson();
        return gson.toJson(this);
    }

    public String toPrettyString() {
        final StringBuilder sb = new StringBuilder("PinnedMessage{");
        sb.append("date=").append(date);
        sb.append(", keyboard=").append(keyboard);
        sb.append(", attachments=").append(attachments);
        sb.append(", fromId=").append(fromId);
        sb.append(", conversationMessageId=").append(conversationMessageId);
        sb.append(", out=").append(out);
        sb.append(", peerId=").append(peerId);
        sb.append(", geo=").append(geo);
        sb.append(", important=").append(important);
        sb.append(", fwdMessages=").append(fwdMessages);
        sb.append(", id=").append(id);
        sb.append(", text='").append(text).append("'");
        sb.append(", replyMessage=").append(replyMessage);
        sb.append('}');
        return sb.toString();
    }
}
